# Generated by Django 6.0.1 on 2026-02-03 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('certification_level', models.CharField(choices=[('OWD', 'Open Water Diver'), ('AOWD', 'Advanced Open Water Diver'), ('RESCUE', 'Rescue Diver'), ('DM', 'Divemaster'), ('NONE', 'Brak certyfikatu')], default='NONE', max_length=10, verbose_name='Certyfikat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil klienta',
                'verbose_name_plural': 'Profile klientów',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa sprzętu')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numer seryjny')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za dobę (PLN)')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Rozmiar/Pojemność')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniego serwisu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.category')),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęt',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data wypożyczenia')),
                ('end_date', models.DateField(verbose_name='Data zwrotu')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt całkowity')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Zwrócono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.customerprofile', verbose_name='Klient')),
                ('equipment', models.ManyToManyField(to='equipment.equipment', verbose_name='Wypożyczony sprzęt')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
    ]
