# Generated by Django 6.0.1 on 2026-02-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNI', 'Uniwersalny'), ('10L', '10 Litrów'), ('12L', '12 Litrów'), ('15L', '15 Litrów')], max_length=10, verbose_name='Rozmiar/Pojemność'),
        ),
    ]
